server:
  port: 8080
  servlet:
    context-path: /springcloud-provider
  tomcat:
    uri-encoding: UTF-8
#mybatis相关配置信息
mybatis:
  mapper-locations: com/zy/cn/mapper/*.xml
  type-aliases-package: com.zy.cn.entity


spring:
  application:
    #应用名称
    name: springcloud-provider
    #mysql相关配置信息
  datasource:
    url: jdbc:mysql://10.0.45.103/mysql-test?characterEncoding=utf8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #http编码格式
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true

#热部署
devtools:
  restart:
    exclude: static/**,templates/**
    enabled: true
  jpa:
    database: MYSQL
    show-sql: true
#在Eureka注册中心进行注册服务
eureka:
  client:
    serviceUrl:
      #注册地址
      defaultZone: http://peer1:1111/eureka/,http://peer3:3333/eureka/,http://peer2:2222/eureka/